app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home_page#index'

  resources :admin, only: [:index]
end

app/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/app/models/admin.rb
# :nodoc:
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :validatable,
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/controllers/admin_controller.rb
# :nodoc:
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/app/controllers/application_controller.rb
# :nodoc:
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_ability
    # change from current_user to current_admin
    @current_ability ||= Ability.new(current_admin)
  end
end

app/app/controllers/home_page_controller.rb
# :nodoc:
class HomePageController < ApplicationController
  def index
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/views/home_page/index.html.slim
.row.transparent
  .col-md-10.offset-md-1
    img.start-image src=image_url('meister_logo.png')

app/app/views/layouts/_footer.html.slim
footer.footer
  nav.navbar.navbar-full.navbar-light.bg-primary.text-uppercase
    #nav-content
      ul.nav.navbar-nav.pull-xs-right
        li.nav-item
          a.nav-link href="#" Impressum
      ul.nav.navbar-nav.pull-xs-left
        li.nav-item
          a.nav-link href="#" Top

app/app/views/layouts/_navbar.html.slim
nav.navbar.navbar-full.navbar-light.bg-primary.text-uppercase
  #nav-content.collapse.navbar-toggleable-xs
    a.navbar-brand href="#" Girolstein Bedachungen
    - if admin_signed_in?
      ul.nav.navbar-nav.pull-xs-left
        li.nav-item
          = link_to('Abmelden', destroy_admin_session_path,
                    method: :delete, class: 'nav-link')
    ul.nav.navbar-nav.pull-xs-right
      li.nav-item
        a.nav-link href="#" Home
      li.nav-item
        a.nav-link  href="#" Flachdach
      li.nav-item
        a.nav-link href="#" Steildach
  button.navbar-toggler.hidden-sm-up[
    data-toggle="collapse"
    data-target="#nav-content"] &#9776;

app/app/views/layouts/application.html.slim
doctype html
html.full
  head
    title Girolstein Bedachungen
    meta charset="utf-8"
    meta[
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    meta http-equiv="x-ua-compatible" content="ie=edge"

    = csrf_meta_tags
    = stylesheet_link_tag('application', media: 'all', \
                          'data-turbolinks-track' => 'reload')
  body
    = render('layouts/navbar')
    .container
      = yield
    = render('layouts/footer')

    = javascript_include_tag('application',
                             'data-turbolinks-track' => 'reload')